
version: '3.9'
services:
    postgres:
        container_name: backdoor_playground_db
        image: postgres:14.6
        restart: always
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        expose:
          - 5432
        volumes: 
          #- ./resources/postgres-data:/var/lib/postgresql/data
          - ./resources/sql/:/docker-entrypoint-initdb.d/